### PR TITLE
fix: consistency level configuration and iterator error handling

### LINKED ISSUE #2: Password for the role resource gets regenerated unexpectedly, causing authentication failure
### What happened?

When one Cassandra node becomes unavailable (e.g., during a restart, node rotation, etc.), the role password gets regenerated unexpectedly, breaking authentication for dependent services.

### How can we reproduce it?

1. Create a Role resource in Cassandra cluster with multiple nodes via provider-cassandra;
2. Restart one Cassandra node;
3. Observe logs with `--debug` option: `Cannot achieve consistency level ALL`
4. Check secret - password was regenerated, authentication fails

### What environment did it happen in?

Crossplane version: v1.20.0
* Kubernetes version: v1.33.4-gke.1350000
* Kubernetes distribution GKE
* Cassandra cluster: multi-node setup
* Provider-cassandra version: v1.11.0

**Fixed in:** https://github.com/arturkasperek/provider-cassandra/pull/1

### PR DESCRIPTION
**Pull request by marushkaa**
### Description of your changes
Current changes fix two connected issues that cause service disruptions and unexpected password regeneration for the roles.cql.cassandra.crossplane.io resource.

I have:
- [X] Read and followed Crossplane's [contribution process].
- [X] Run tests via go test
- [X] Code compiles and runs locally
- [X] Functionality verified in my environment with a 3-node Cassandra cluster
- [X] Run `make reviewable` to ensure this PR is ready for review. Note: CRDs generated manually with controller-gen
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

**Problem:**
Currently, the provider uses a hardcoded ALL as the consistency level, which causes errors ("Cannot achieve consistency level ALL") during one of the Cassandra node restarts. When one of the Cassandra nodes becomes unavailable, the provider regenerates passwords for existing roles, causing authentication failures for dependent services.

**Steps to reproduce:**
1. Cassandra node restart → consistency level ALL fails;
2. Scan() returns false (error, not "no rows");
3. Iterator not closed properly;
4. Observe() returns ResourceExists: false;
5. Crossplane calls Create() for existing role;
6. Password regenerates;
8. Dependent service authentication fails;

**Proposal**:
- Add `consistencyLevel` field to `ProviderConfig` api, which supports all levels, and let users choose one, that suits them (set default to QUORUM instead of ALL (requires 2/3 replicas, more softly tolerates node failures));
- Properly close the iterator before early return when Scan() fails;
- Use named error to allow defer to modify the return value;

Fixes [issue](https://github.com/arturkasperek/provider-cassandra/issues/2)

### CODE REVIEW

File: apis/v1alpha1/providerconfig_types.go [hunk 1]
```diff
@@ -29,6 +29,8 @@ import (
 type ProviderConfigSpec struct {
 	// Credentials required to authenticate to this provider.
 	Credentials ProviderCredentials `json:"credentials"`
+	// ConsistencyLevel defines the consistency level for Cassandra operations.
+	ConsistencyLevel *string `json:"consistencyLevel,omitempty"`
```
Comment (arturkasperek) [inline apis/v1alpha1/providerconfig_types.go:33]: @marushkaa I propose to use as a default `ALL` to keep the previous behavior

**Comment by arturkasperek** [comment]
@marushkaa please check this job https://github.com/arturkasperek/provider-cassandra/actions/runs/18555504176/job/52892469576 - it failed

File: apis/v1alpha1/providerconfig_types.go (hunk 1 above)
Comment (marushkaa) [reply apis/v1alpha1/providerconfig_types.go:33]: @arturkasperek I've set `ALL` as the default consistency level, as you suggested, to avoid causing breaking changes. 
However, I'd like to note that `QUORUM` could be a better option for production environments. When topology changes happen in the cluster (a node restarts, pod rescheduling, network partitions, etc.), `ALL` is quite strict. `QUORUM` provides a more resilient behavior while guaranteeing a good level of consistency.
For this reason, I propose to leave`QUORUM` as an example option in the appropriate section of the docs (ProviderConfig example).

Comment (arturkasperek) [reply apis/v1alpha1/providerconfig_types.go:33]: ok - example is fine

**Comment by marushkaa** [comment]
> @marushkaa please check this job [arturkasperek/provider-cassandra/actions/runs/18555504176/job/52892469576](https://github.com/arturkasperek/provider-cassandra/actions/runs/18555504176/job/52892469576) - it failed

@arturkasperek I've generated the missing ProviderConfig CRD and added it to PR. Could you re-run check workflow, please?

**Comment by arturkasperek** [comment]
@marushkaa now it passed :-).  Since you already work on that project, can you btw update that package https://github.com/arturkasperek/provider-cassandra/actions/runs/18556248368/job/52896741880 - right now publish step stopped to work. And I guess for you it's important to publish a new version :D

**Comment by arturkasperek** [comment]
@marushkaa it's published https://marketplace.upbound.io/providers/arturkasperek-org/provider-cassandra/v0.1.2
